name: build-caddy-admin-ui
on:
  push:
    branches:
      - dev
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v2
        with:
          useLockFile: false
          working-directory: "web"
          install-command: npm install

      - name: ğŸ— Run build script
        working-directory: "web"
        run: npm run build
      
      - name: ğŸ“¦ Move build
        run: |
          mkdir main
          cp -r web/out main/
          cp -r screenshots main/
          cp caddy_admin_ui.go go.mod go.sum README.md main/

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main # The branch the action should deploy to.
          folder: "main" # The folder the action should deploy.
