name: build-caddy-admin-ui
on:
  push:
    branches:
      - dev
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: ğŸ“¥ Download deps
        working-directory: "web"
        run: |
          bun install

      - name: ğŸ— Run build script
        working-directory: "web"
        run: bun run build
      
      - name: ğŸ“¦ Move build
        run: |
          mkdir main
          cp -r web/out main/build
          cp -r screenshots main/
          cp caddy_admin_ui.go webshell.go go.mod go.sum README.md main/

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: main # The branch the action should deploy to.
          folder: "main" # The folder the action should deploy.
